### ISSUE TITLE
IndexError with emotiv.py

### ISSUE THREAD

**Issue by ppasler** [openyou/emokit#157]
Hi guys,

I just found your project and tried it out.
If I start the emotiv script with idle I get the following error on startup

```python
Windows detected.
True
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gevent-1.0.2-py2.7-win32.egg\gevent\greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "C:\emotiv.py", line 556, in setup_crypto
    k[0] = sn[-1]
IndexError: string index out of range
<Greenlet at 0x31a8760: <bound method Emotiv.setup_crypto of <__main__.Emotiv object at 0x031B03F0>>('')> failed with IndexError
```

All values are zero, although have good signal with the Emotiv Software

```python
Packets Received: 0 Packets Processed: 0
Y Reading: 0 Quality: 0
F3 Reading: 0 Quality: 0
F4 Reading: 0 Quality: 0
P7 Reading: 0 Quality: 0
FC6 Reading: 0 Quality: 0
F7 Reading: 0 Quality: 0
F8 Reading: 0 Quality: 0
T7 Reading: 0 Quality: 0
P8 Reading: 0 Quality: 0
FC5 Reading: 0 Quality: 0
AF4 Reading: 0 Quality: 0
Unknown Reading: 0 Quality: 0
T8 Reading: 0 Quality: 0
X Reading: 0 Quality: 0
O2 Reading: 0 Quality: 0
O1 Reading: 0 Quality: 0
AF3 Reading: 0 Quality: 0
Battery: 0
```

I guess the error prevents the script to work right.  I use the EPOC+, Windows 7 and python 2.7.10

Does anyone have an idea how to solve this or where this error comes from?

Thanks in advance, paul

**Comment by ppasler** [comment]
Sometimes ready all other issues helps  [#138](https://github.com/openyou/emokit/issues/138)... sorry for raising an Issue.

I changes the "def setup_windows" to the one from the fork here:
https://github.com/a455bcd9/emokit/blob/master/python/emokit/emotiv.py

The error is gone and values appear.
