### ISSUE TITLE
Issue with running mousecontrol.py

### ISSUE THREAD

**Issue by wardiv** [openyou/emokit#275]
Hi, I have been trying to run mouse control.py from https://github.com/nikhiljay/brainwaves/tree/master/emokit/python and I am getting following error. 

`Traceback (most recent call last):
  File "/Users/divz/anaconda/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/divz/Documents/brainwaves-master/emokit/python/emokit/emotiv.py", line 425, in setup
    self.setup_darwin()
  File "/Users/divz/Documents/brainwaves-master/emokit/python/emokit/emotiv.py", line 552, in setup_darwin
    data = hidraw.read(34)
  File "hid.pyx", line 105, in hid.device.read (hid.c:2338)
ValueError: not open
<Greenlet at 0x102591e10: <bound method Emotiv.setup of <emokit.emotiv.Emotiv object at 0x10218d510>>> failed with ValueError

Traceback (most recent call last):
  File "mouse_control.py", line 79, in <module>
    main()
  File "mouse_control.py", line 50, in main
    screen = Xlib()
  File "mouse_control.py", line 16, in __init__
    self.xlib = ctypes.cdll.LoadLibrary('libX11.dylib')
  File "/Users/divz/anaconda/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Users/divz/anaconda/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libX11.dylib, 6): image not found`

Any help would be appreciated. Thanks in advance !

**Comment by warrenarea** [comment]
I haven't done much experimenting with the Linux portion of emokit.

However, if I had to make an educated guess, I would say, the issue lays with 
it not finding an appropriate library.
```
libX11.dylib
```
I would investigate why its not loading that library.
also... it looks like you're using something from another repository... 
so it just might not be compatible with the Epoc+ as well... so it might not
be detecting the correct USB device as well... and the Epoc+ has a different
gyro configuration as well... so that other repository probably wouldn't work
if you're using the Epoc+
