### ISSUE TITLE
Unable to connect to device

### ISSUE THREAD

**Issue by Yuri-V** [openyou/emokit#96]
Issue is much similar to #86 , but solution, presented there, didn's work for me.

I'm using python 2.7.5 on x86 WinXP
Attempting to run the render.py

Trace:
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\gevent\greenlet.py", line 390, in run
result = self.run(self.args, *self.kwargs)
File "C:\Python27\lib\site-packages\emokit-0.0.1-py2.7.egg\emokit\emotiv.py", line 351, in setup
self.setupWin()
File "C:\Python27\lib\site-packages\emokit-0.0.1-py2.7.egg\emokit\emotiv.py", line 406, in setupWin
for device in hid.findall_hid_devices():
File "build\bdist.win32\egg\pywinusb\hid\core.py", line 121, in find_all_hid_devices
with winapi.DeviceInterfaceSetInfo(guid) as h_info:
File "build\bdist.win32\egg\pywinusb\hid\winapi.py", line 428, in enter
return self.open()
File "build\bdist.win32\egg\pywinusb\hid\winapi.py", line 439, in open
(DIGCF.PRESENT | DIGCF.DEVICEINTERFACE) )
ArgumentError: argument 3: : wrong type
>> failed with ArgumentError

**Comment by bschumacher** [comment]
Latest version should fix your problem, open a new issue if it does not.
